#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
apt-get install haproxy=2.5.\*

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 180950-web-01 54.85.13.165:80 check\n\tserver 180950-web-02 174.129.55.119:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
